/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AccessControl"): TruffleContracts.AccessControlContract;
      require(name: "ERC20"): TruffleContracts.ERC20Contract;
      require(name: "ERC20Burnable"): TruffleContracts.ERC20BurnableContract;
      require(name: "ERC20Pausable"): TruffleContracts.ERC20PausableContract;
      require(
        name: "ERC20PresetMinterPauser"
      ): TruffleContracts.ERC20PresetMinterPauserContract;
      require(name: "GLDToken"): TruffleContracts.GLDTokenContract;
      require(name: "IERC20"): TruffleContracts.IERC20Contract;
      require(name: "Pausable"): TruffleContracts.PausableContract;
      require(name: "test"): TruffleContracts.testContract;
      require(name: "TFCToken"): TruffleContracts.TFCTokenContract;
      require(
        name: "TurboFieldFactory"
      ): TruffleContracts.TurboFieldFactoryContract;
      require(
        name: "TurboFieldRoleSet"
      ): TruffleContracts.TurboFieldRoleSetContract;
      require(
        name: "TurboFieldSector"
      ): TruffleContracts.TurboFieldSectorContract;
    }
  }
}
