/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { AccessControlContract } from "./AccessControl";
import { Erc20Contract } from "./Erc20";
import { Erc20MinterPauserBurnerContract } from "./Erc20MinterPauserBurner";
import { Erc20PausableContract } from "./Erc20Pausable";
import { Ierc20Contract } from "./Ierc20";
import { PausableContract } from "./Pausable";
import { TfcManagerContract } from "./TfcManager";
import { TfcTokenContract } from "./TfcToken";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AccessControl"): AccessControlContract;
      require(name: "ERC20"): Erc20Contract;
      require(name: "ERC20MinterPauserBurner"): Erc20MinterPauserBurnerContract;
      require(name: "ERC20Pausable"): Erc20PausableContract;
      require(name: "IERC20"): Ierc20Contract;
      require(name: "Pausable"): PausableContract;
      require(name: "TFCManager"): TfcManagerContract;
      require(name: "TFCToken"): TfcTokenContract;
    }
  }
}

export { AccessControlContract, AccessControlInstance } from "./AccessControl";
export { Erc20Contract, Erc20Instance } from "./Erc20";
export {
  Erc20MinterPauserBurnerContract,
  Erc20MinterPauserBurnerInstance
} from "./Erc20MinterPauserBurner";
export { Erc20PausableContract, Erc20PausableInstance } from "./Erc20Pausable";
export { Ierc20Contract, Ierc20Instance } from "./Ierc20";
export { PausableContract, PausableInstance } from "./Pausable";
export { TfcManagerContract, TfcManagerInstance } from "./TfcManager";
export { TfcTokenContract, TfcTokenInstance } from "./TfcToken";
